Repository StephaneGrabsia/Cooding, pull requests merged in 2022-12, with the labels that each got.

#9 Api setup
  .github/linters/.flake8
  .github/workflows/super-linter.yml
  .github/workflows/test.yml
  back/api/__init__.py
  back/api/admin.py
  back/api/apps.py
  back/api/migrations/0001_initial.py
  back/api/migrations/0002_rename_name_user_username.py
  back/api/migrations/0003_student_teacher_user_is_student_user_is_teacher.py
  back/api/migrations/0004_delete_member_remove_user_is_student_and_more.py
  back/api/migrations/__init__.py
  back/api/models.py
  back/api/serializers.py
  back/api/tests.py
  back/api/urls.py
  back/api/views.py
  back/pyproject.toml
  back/uQuizz/__pycache__/__init__.cpython-39.pyc
  back/uQuizz/__pycache__/settings.cpython-39.pyc
  back/uQuizz/__pycache__/urls.cpython-39.pyc
  back/uQuizz/settings.py
  back/uQuizz/urls.py
Labels: WIP, backend

#12 Teacher API Views
  back/api/migrations/0001_initial.py
  back/api/models.py
  back/api/serializers.py
  back/api/tests.py
  back/api/urls.py
  back/api/views.py
  back/uQuizz/settings.py
Labels: backend, need FR, CRed

#8 Front login components
  front/.eslintrc.json
  front/Dockerfile
  front/package.json
  front/public/index.html
  front/src/app.js
  front/src/assets/background.svg
  front/src/assets/icon.svg
  front/src/assets/icon_coody.svg:Zone.Identifier
  front/src/assets/logo.svg
  front/src/assets/logo.svg:Zone.Identifier
  front/src/assets/text.svg
  front/src/components/login_forms.js
  front/src/components/register_form.js
  front/src/containers/index.js
  front/src/styles/style.scss
  front/webpack.config.js
Labels: WIP, frontend, CRed, FRed

#14 Backend refactor
  back/api/admin.py
  back/api/apps.py
  back/api/decorators.py
  back/api/migrations/0001_initial.py
  back/api/migrations/0002_teacher_date_joined_teacher_first_name_and_more.py
  back/api/models.py
  back/api/serializers.py
  back/api/tests.py
  back/api/urls.py
  back/api/views.py
  back/uQuizz/settings.py
  back/uQuizz/urls.py
Labels: backend, need CR, need FR

#15 install react router dom
  front/package.json
  front/public/index.html
  front/webpack.config.js
Labels: frontend, need CR, need FR

#16 Classroom API View
  back/api/migrations/0001_initial.py
  back/api/migrations/0002_remove_classroom_id_alter_classroom_room_id.py
  back/api/migrations/0002_teacher_date_joined_teacher_first_name_and_more.py
  back/api/models.py
  back/api/serializers.py
  back/api/tests.py
  back/api/urls.py
  back/api/views.py
Labels: backend, CRed, able to merge

#18 Login student
  front/src/app.js
  front/src/components/login_forms.js
  front/src/components/register_form.js
  front/src/containers/TeacherIndex.js
  front/src/containers/index.js
  front/src/containers/register.js
  front/src/context/AuthContext.js
  front/src/utils/PrivateRoute.js
Labels: frontend, need CR, need FR

#17 Student API Views
  back/api/serializers.py
  back/api/tests.py
  back/api/urls.py
  back/api/views.py
Labels: backend, need FR, CRed
