Repository StephaneGrabsia/Cooding, pull requests merged in 2023-02, with the labels that each got.

#34 fix dockerfile
  back/Dockerfile
Labels: bug, able to merge

#33 Fixing issue with solutions
  back/api/views.py
  front/src/components/appBar.js
Labels: bug, frontend, backend, CRed, able to merge

#36 Wrapping student page for teacher
  back/api/views.py
  front/src/app.js
  front/src/components/Avatar.js
  front/src/components/teacherDashboard/Content.js
  front/src/components/teacherDashboard/Header.js
  front/src/components/teacherDashboard/ItemCard.js
  front/src/components/teacherDashboard/PreviewPage.js
  front/src/components/teacherDashboard/TeacherNavigator.js
  front/src/containers/TeacherIndex.js
  front/src/containers/TeacherPage.js
  front/src/context/AuthContext.js
Labels: frontend, need FR

#37 Exercise form
  back/api/urls.py
  back/api/views.py
  front/src/components/teacherDashboard/Content.js
  front/src/components/teacherDashboard/ExerciseForm.js
  front/src/components/teacherDashboard/ItemCard.js
  front/src/components/teacherDashboard/PreviewPage.js
Labels: WIP, frontend, backend, need FR

#38 Update button on exercise form
  back/api/models.py
  back/api/tests.py
  back/api/urls.py
  back/api/views.py
  front/src/components/teacherDashboard/Content.js
  front/src/components/teacherDashboard/ExerciseForm.js
  front/src/components/teacherDashboard/ItemCard.js
Labels: frontend, backend, need CR, need FR

#40 Checking if user already connected in login page to redirect him
  front/src/containers/index.js
Labels: frontend, FRed, able to merge

#41 Adding favicon and changing tab title
  front/public/favicon.ico
  front/public/index.html
Labels: frontend, CRed, FRed, able to merge

#42 Splitting of teacher dashboard
  front/src/app.js
  front/src/components/Avatar.js
  front/src/components/teacherDashboard/ClassroomsContent.js
  front/src/components/teacherDashboard/ExerciseContent.js
  front/src/components/teacherDashboard/ExerciseForm.js
  front/src/components/teacherDashboard/ItemCardClassroom.js
  front/src/components/teacherDashboard/ItemCardExercise.js
  front/src/components/teacherDashboard/TeacherNavigator.js
  front/src/containers/ClassroomsTeacherPage.js
  front/src/containers/ExercisesTeacherPage.js
  front/src/containers/index.js
  front/src/containers/studentPage.js
  front/src/context/AuthContext.js
  front/src/utils/PrivateRoute.js
Labels: WIP, frontend, backend

#47 Classroom front cards
  back/api/views.py
  front/src/components/teacherDashboard/ClassroomsContent.js
  front/src/components/teacherDashboard/ItemCardClassroom.js
Labels: frontend, backend, need FR

#51 fix bug delete classroom
  back/api/models.py
Labels: bug, backend
