Repository StephaneGrabsia/Cooding, pull requests merged in 2023-01, with the labels that each got.

#13 Second version of the main page design.
  front/package.json
  front/src/app.js
  front/src/assets/needHelp.jpg
  front/src/assets/shiba_running.jpg
  front/src/components/appBar.js
  front/src/containers/studentPage.js
  front/src/styles/markdown-styles.css
  front/src/styles/style.css
  front/webpack.config.js
Labels: WIP, frontend, CRed, FRed

#19 Register form
  front/src/components/RegisterForm.js
  front/src/components/register_form.js
  front/src/containers/index.js
  front/src/containers/register.js
  front/src/context/AuthContext.js
Labels: frontend, need CR, need FR, URGENT

#21 fix back dockerfile
  back/Dockerfile
Labels: bug

#23 Api setup
  back/api/migrations/0003_alter_solution_exercise_alter_solution_student.py
  back/api/models.py
  back/api/serializers.py
  back/api/tests.py
  back/api/urls.py
  back/api/views.py
Labels: WIP, backend, need CR

#22 Student main page front
  front/src/assets/coin.png
  front/src/assets/needHelp.svg
  front/src/assets/shiba_running.svg
  front/src/assets/surf.png
  front/src/components/RegisterForm.js
  front/src/components/appBar.js
  front/src/components/login_forms.js
  front/src/components/outputSectionBar.js
  front/src/containers/studentPage.js
  front/src/context/AuthContext.js
Labels: frontend, need FR, CRed

#28 Fixing React CI by going back to former versions of dependences
  .gitignore
  front/package-lock.json
Labels: bug, URGENT

#25 Api setup
  back/api/migrations/0006_remove_solution_output.py
  back/api/models.py
  back/api/serializers.py
  back/api/tests.py
  back/api/views.py
  front/src/context/AuthContext.js
Labels: backend, CRed, FRed, able to merge
